"""RLS policies and the partitioned chunk_embedding table.

Kept separate from the autogenerated schema migration on purpose: this file is the
authorization boundary, and it should be reviewable as SQL rather than buried in
generated output.

Revision ID: 0002_rls_embed
Revises: 388b2efa5820
"""

from alembic import op

from corpus.db.rls import POLICY_ROLES, disable_rls_sql, enable_rls_sql, tenant_scoped_tables

revision = "0002_rls_embed"
down_revision = "388b2efa5820"
branch_labels = None
depends_on = None

EMBEDDING_DIM = 768


def upgrade() -> None:
    # ---- chunk_embedding, partitioned by model_version -------------------
    # Partitioning is the re-embedding plan. A model change means rebuilding 14M
    # vectors; with LIST partitioning the new set is built into a fresh partition
    # alongside the live one and swapped, instead of UPDATE-ing every row in place.
    #
    # halfvec rather than vector: 2 bytes/dimension instead of 4, negligible recall
    # loss, and HNSW indexes halfvec up to 4000 dimensions vs 2000 for vector.
    op.execute(
        f"""
        CREATE TABLE chunk_embedding (
            chunk_id      uuid  NOT NULL REFERENCES chunk(id) ON DELETE CASCADE,
            tenant_id     uuid  NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
            model_version text  NOT NULL,
            embedding     halfvec({EMBEDDING_DIM}) NOT NULL,
            created_at    timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (model_version, chunk_id)
        ) PARTITION BY LIST (model_version)
        """
    )
    # A default partition means an unknown model_version is a loud constraint
    # violation at swap time rather than a silent write into nowhere.
    op.execute("CREATE TABLE chunk_embedding_default PARTITION OF chunk_embedding DEFAULT")
    op.execute("CREATE INDEX ix_chunk_embedding_tenant ON chunk_embedding (tenant_id)")

    # No HNSW index yet. Building one before there are vectors to build it from
    # would only be wrong: the graph is built once, from the data present.

    # ---- row-level security ---------------------------------------------
    tables = [*tenant_scoped_tables(), "chunk_embedding"]
    roles = ", ".join(POLICY_ROLES)
    for table in tables:
        for stmt in enable_rls_sql(table):
            op.execute(stmt)
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO {roles}")

    # The tenant table itself is not tenant-scoped, but the application roles need
    # to read it to resolve a slug to an id.
    op.execute(f"GRANT SELECT ON tenant TO {roles}")


def downgrade() -> None:
    tables = [*tenant_scoped_tables(), "chunk_embedding"]
    for table in tables:
        for stmt in disable_rls_sql(table):
            op.execute(stmt)
    op.execute("DROP TABLE IF EXISTS chunk_embedding CASCADE")
