"""initial schema, entities, RLS

Revision ID: 388b2efa5820
Revises:
Create Date: 2026-08-20 16:38:09.198769

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "388b2efa5820"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "entity",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "vendor",
                "person",
                "technique",
                "regulation",
                "product",
                "organization",
                name="entity_kind",
            ),
            nullable=False,
        ),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "kind", "canonical_name", name="uq_entity_tenant_kind_name"
        ),
    )
    op.create_index(op.f("ix_entity_kind"), "entity", ["kind"], unique=False)
    op.create_index(op.f("ix_entity_tenant_id"), "entity", ["tenant_id"], unique=False)
    op.create_table(
        "heartbeat",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("flow_name", sa.String(length=128), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=32), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "flow_name", name="uq_heartbeat_flow"),
    )
    op.create_index(op.f("ix_heartbeat_tenant_id"), "heartbeat", ["tenant_id"], unique=False)
    op.create_table(
        "purge_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("rows_deleted", sa.BigInteger(), nullable=True),
        sa.Column(
            "performed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_purge_log_tenant_id"), "purge_log", ["tenant_id"], unique=False)
    op.create_table(
        "source",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "youtube_channel", "youtube_playlist", "rss", "arxiv", "web", name="source_kind"
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column(
            "authority_tier",
            sa.Enum(
                "peer_reviewed",
                "primary_regulatory",
                "vendor_official",
                "established_media",
                "practitioner",
                "aggregator",
                "unknown",
                name="authority_tier",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "deprecated", "purged", name="source_status"),
            nullable=False,
        ),
        sa.Column("deprecated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "kind", "external_id", name="uq_source_tenant_kind_external"
        ),
    )
    op.create_index(op.f("ix_source_status"), "source", ["status"], unique=False)
    op.create_index(op.f("ix_source_tenant_id"), "source", ["tenant_id"], unique=False)
    op.create_table(
        "document",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "published_at_precision",
            sa.Enum("exact", "date", "month", "year", "inferred", "unknown", name="date_precision"),
            nullable=False,
        ),
        sa.Column("published_at_source", sa.String(length=32), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("raw_ref", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "enriched", "failed", "purged", name="document_status"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "source_id", "external_id", name="uq_document_tenant_source_external"
        ),
    )
    op.create_index(op.f("ix_document_content_hash"), "document", ["content_hash"], unique=False)
    op.create_index(
        "ix_document_published", "document", ["tenant_id", "published_at"], unique=False
    )
    op.create_index(op.f("ix_document_source_id"), "document", ["source_id"], unique=False)
    op.create_index(op.f("ix_document_status"), "document", ["status"], unique=False)
    op.create_index(op.f("ix_document_tenant_id"), "document", ["tenant_id"], unique=False)
    op.create_table(
        "ingest_state",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("cursor", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingest_state_source_id"), "ingest_state", ["source_id"], unique=False)
    op.create_index(op.f("ix_ingest_state_tenant_id"), "ingest_state", ["tenant_id"], unique=False)
    op.create_table(
        "document_summary",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("extractive_textrank", "abstractive_llm", name="summary_method"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=768), nullable=True),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "method", name="uq_summary_doc_method"),
    )
    op.create_index(
        op.f("ix_document_summary_document_id"), "document_summary", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_summary_tenant_id"), "document_summary", ["tenant_id"], unique=False
    )
    op.create_table(
        "speaker",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("canonical_entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "attribution_method",
            sa.Enum(
                "diarized",
                "channel_default",
                "title_parsed",
                "description_parsed",
                "unknown",
                name="attribution_method",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["canonical_entity_id"], ["entity.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_speaker_document_id"), "speaker", ["document_id"], unique=False)
    op.create_index(op.f("ix_speaker_tenant_id"), "speaker", ["tenant_id"], unique=False)
    op.create_table(
        "transcript_version",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "supadata",
                "ytapi",
                "whisper_local",
                "restored",
                "native",
                name="transcript_provider",
            ),
            nullable=False,
        ),
        sa.Column("is_auto_generated", sa.Boolean(), nullable=True),
        sa.Column(
            "provenance_confidence",
            sa.Enum("known", "inferred", "unknown", name="provenance_confidence"),
            nullable=False,
        ),
        sa.Column("lang", sa.String(length=16), nullable=False),
        sa.Column("available_langs", postgresql.ARRAY(sa.String(length=16)), nullable=True),
        sa.Column("derived_from_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(is_auto_generated IS NULL) = (provenance_confidence = 'unknown')",
            name="ck_transcript_provenance_consistent",
        ),
        sa.ForeignKeyConstraint(["derived_from_id"], ["transcript_version.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "document_id", "provider", "lang", name="uq_transcript_doc_provider_lang"
        ),
    )
    op.create_index(
        op.f("ix_transcript_version_document_id"),
        "transcript_version",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_version_tenant_id"), "transcript_version", ["tenant_id"], unique=False
    )
    op.create_table(
        "chunk",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("transcript_version_id", sa.UUID(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.BigInteger(), nullable=True),
        sa.Column("end_ms", sa.BigInteger(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("speaker_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["speaker_id"], ["speaker.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["transcript_version_id"], ["transcript_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transcript_version_id", "idx", name="uq_chunk_version_idx"),
    )
    op.create_index(op.f("ix_chunk_document_id"), "chunk", ["document_id"], unique=False)
    op.create_index(op.f("ix_chunk_tenant_id"), "chunk", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_chunk_transcript_version_id"), "chunk", ["transcript_version_id"], unique=False
    )
    op.create_table(
        "segment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("transcript_version_id", sa.UUID(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("offset_ms", sa.BigInteger(), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["transcript_version_id"], ["transcript_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transcript_version_id", "idx", name="uq_segment_version_idx"),
    )
    op.create_index(op.f("ix_segment_tenant_id"), "segment", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_segment_transcript_version_id"), "segment", ["transcript_version_id"], unique=False
    )
    op.create_table(
        "utterance",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("speaker_id", sa.UUID(), nullable=False),
        sa.Column("start_ms", sa.BigInteger(), nullable=False),
        sa.Column("end_ms", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["speaker_id"], ["speaker.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_utterance_document_id"), "utterance", ["document_id"], unique=False)
    op.create_index(op.f("ix_utterance_speaker_id"), "utterance", ["speaker_id"], unique=False)
    op.create_index(op.f("ix_utterance_tenant_id"), "utterance", ["tenant_id"], unique=False)
    op.create_table(
        "entity_mention",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=True),
        sa.Column("speaker_id", sa.UUID(), nullable=True),
        sa.Column("surface", sa.Text(), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=True),
        sa.Column("end_char", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("extractor_version", sa.String(length=128), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunk.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entity_id"], ["entity.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["speaker_id"], ["speaker.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entity_mention_document_id"), "entity_mention", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_entity_mention_entity_id"), "entity_mention", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_entity_mention_tenant_id"), "entity_mention", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_mention_entity_doc",
        "entity_mention",
        ["tenant_id", "entity_id", "document_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mention_entity_doc", table_name="entity_mention")
    op.drop_index(op.f("ix_entity_mention_tenant_id"), table_name="entity_mention")
    op.drop_index(op.f("ix_entity_mention_entity_id"), table_name="entity_mention")
    op.drop_index(op.f("ix_entity_mention_document_id"), table_name="entity_mention")
    op.drop_table("entity_mention")
    op.drop_index(op.f("ix_utterance_tenant_id"), table_name="utterance")
    op.drop_index(op.f("ix_utterance_speaker_id"), table_name="utterance")
    op.drop_index(op.f("ix_utterance_document_id"), table_name="utterance")
    op.drop_table("utterance")
    op.drop_index(op.f("ix_segment_transcript_version_id"), table_name="segment")
    op.drop_index(op.f("ix_segment_tenant_id"), table_name="segment")
    op.drop_table("segment")
    op.drop_index(op.f("ix_chunk_transcript_version_id"), table_name="chunk")
    op.drop_index(op.f("ix_chunk_tenant_id"), table_name="chunk")
    op.drop_index(op.f("ix_chunk_document_id"), table_name="chunk")
    op.drop_table("chunk")
    op.drop_index(op.f("ix_transcript_version_tenant_id"), table_name="transcript_version")
    op.drop_index(op.f("ix_transcript_version_document_id"), table_name="transcript_version")
    op.drop_table("transcript_version")
    op.drop_index(op.f("ix_speaker_tenant_id"), table_name="speaker")
    op.drop_index(op.f("ix_speaker_document_id"), table_name="speaker")
    op.drop_table("speaker")
    op.drop_index(op.f("ix_document_summary_tenant_id"), table_name="document_summary")
    op.drop_index(op.f("ix_document_summary_document_id"), table_name="document_summary")
    op.drop_table("document_summary")
    op.drop_index(op.f("ix_ingest_state_tenant_id"), table_name="ingest_state")
    op.drop_index(op.f("ix_ingest_state_source_id"), table_name="ingest_state")
    op.drop_table("ingest_state")
    op.drop_index(op.f("ix_document_tenant_id"), table_name="document")
    op.drop_index(op.f("ix_document_status"), table_name="document")
    op.drop_index(op.f("ix_document_source_id"), table_name="document")
    op.drop_index("ix_document_published", table_name="document")
    op.drop_index(op.f("ix_document_content_hash"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_source_tenant_id"), table_name="source")
    op.drop_index(op.f("ix_source_status"), table_name="source")
    op.drop_table("source")
    op.drop_index(op.f("ix_purge_log_tenant_id"), table_name="purge_log")
    op.drop_table("purge_log")
    op.drop_index(op.f("ix_heartbeat_tenant_id"), table_name="heartbeat")
    op.drop_table("heartbeat")
    op.drop_index(op.f("ix_entity_tenant_id"), table_name="entity")
    op.drop_index(op.f("ix_entity_kind"), table_name="entity")
    op.drop_table("entity")
    op.drop_table("tenant")
    # ### end Alembic commands ###

    # sa.Enum creates these types on upgrade, but autogenerate never emits the
    # matching DROP. Without this, `downgrade base` leaves them behind and the next
    # `upgrade head` fails with "type already exists" — the migration is not
    # round-trippable, which only shows up the first time someone rebuilds from
    # scratch.
    op.execute("DROP TYPE IF EXISTS attribution_method CASCADE")
    op.execute("DROP TYPE IF EXISTS authority_tier CASCADE")
    op.execute("DROP TYPE IF EXISTS date_precision CASCADE")
    op.execute("DROP TYPE IF EXISTS document_status CASCADE")
    op.execute("DROP TYPE IF EXISTS entity_kind CASCADE")
    op.execute("DROP TYPE IF EXISTS provenance_confidence CASCADE")
    op.execute("DROP TYPE IF EXISTS source_kind CASCADE")
    op.execute("DROP TYPE IF EXISTS source_status CASCADE")
    op.execute("DROP TYPE IF EXISTS summary_method CASCADE")
    op.execute("DROP TYPE IF EXISTS transcript_provider CASCADE")
