#!/usr/bin/env python
"""Consolidate the three verified channel lists into one seed table.

Reads verified bronze data (real channel_id/handle/subscriber counts from Supadata
and yt-dlp) and applies the keep/cut/domain/tier decisions made across three rounds
of review. One-time build step, not part of the ingest pipeline — its output,
seeds/youtube_channels.yaml, is what ingestion (step 3) actually reads.

Re-run after a fresh channel survey; domain and authority_tier are meant to be
hand-tuned in the YAML afterward, so a re-run should be reviewed as a diff, not
applied blindly.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

from corpus.config import get_settings

BRONZE = get_settings().bronze_dir / "channels"

HEADER = """\
# YouTube channel seed table. Generated by scripts/build_channel_seeds.py — see
# seeds/README.md for the ingestion ramp and how to regenerate.
#
# 155 unique channels across three verified rounds, deduplicated by handle. Full
# backfill is ~63,300 credits: 2.1 months at the 30,000/month Supadata budget.
#
# domain and authority_tier are meant to be hand-tuned here over time; edit freely.
# Everything else is a point-in-time survey fact from 2026-08-21 — re-run this
# script against fresh bronze data rather than hand-editing it.
#
# phase, in ingestion order:
#   research-p1            vendor primaries + interviews + news + engineering practice
#   subscriptions          verified subscriptions, deduped against research-p1/p2
#   automation             the automation/creator-business tier
#   research-p2            the rest of the research tier
#   research-p3-deferred   AWS only — ingest by curated playlist, never by channel
"""

RESEARCH_TIER_MAP: dict[str, tuple[str, str] | None] = {
    "vendor_primary": ("vendor_official", "research-p1"),
    "interviews_positions": ("established_media", "research-p1"),
    "news_analysis": ("established_media", "research-p1"),
    "engineering_practice": ("practitioner", "research-p1"),
    "foundations_safety": ("established_media", "research-p2"),
    "mixed_caution": ("established_media", "research-p2"),
    "excluded_hype": None,  # excluded deliberately
}

PHASE1_HANDLES = {
    "anthropic-ai",
    "openai",
    "googledeepmind",
    "huggingface",
    "mistralai_",
    "aiatmeta",
    "dwarkeshpatel",
    "latentspacepod",
    "machinelearningstreettalk",
    "nopriorspodcast",
    "cognitiverevolutionpodcast",
    "sequoiacapital",
    "hardfork",
    "aiexplained-official",
    "natebjones",
    "lastweekinai",
    "dralandthompson",
    "andrejkarpathy",
    "arp_ai",
    "umarjamilai",
    "donatocapitella",
    "samwitteveenai",
    "colemedin",
    "indydevdan",
}

AUTOMATION_EXCLUDE = {"juliangoldieseo", "zapier"}

SUB_AI_RESEARCH = {
    "aiDotEngineer": "practitioner",  # conference talks — highest value on the list
}
SUB_AI_AUTOMATION = {
    "AAIFLive-x1r": "practitioner",
    "betterstack": "vendor_official",
    "tessl-ai": "vendor_official",
    "aisamsonreal": "practitioner",
    "BrockMesarich": "practitioner",
    "aivideoschool": "practitioner",
    "growproduct": "practitioner",
    "BartSlodyczka": "practitioner",
    "andylokcl": "practitioner",
    "AIFoundersHQ": "practitioner",
    "bo-sar": "practitioner",
    "ai_guy": "aggregator",
    "vrsen": "practitioner",
    "BenAI92": "practitioner",
    "AdamGoodyer": "practitioner",
    "beinnyule": "practitioner",
    "AI.Tooltip": "practitioner",
    "AgentZeroFW": "vendor_official",
    "Blake-Harkness": "practitioner",
    "AryanXMahajan": "practitioner",
    "AdsHarley": "practitioner",
    "ArtemXTech": "practitioner",
    "aiwithremy": "practitioner",
}
SUB_ENTREPRENEURSHIP = {
    "THEREALBRADLEA": "practitioner",
    "chris.haroun": "practitioner",
    "AlexHormozi": "practitioner",
    "AJSmart": "practitioner",
    "alekSheffy": "practitioner",
    "PodcastBigDeal": "practitioner",
    "Adamerhartvideo": "practitioner",
    "alexbsheridan": "practitioner",
    "alexmicol": "aggregator",
    "TheBrettWay": "practitioner",
    "alex1beck": "practitioner",
    "AndresTheDesigner": "practitioner",
    "alvarogellings": "practitioner",
    "CalebRalston": "practitioner",
    "chrisdonnellybusiness": "practitioner",
    "AlexStephenLieberman": "practitioner",
}
SUB_PERSONAL_DEV = {
    "aliabdaal": "established_media",
    "hubermanlab": "established_media",
    "Charismaoncommand": "established_media",
    "alexanderlyon": "practitioner",
    "BrockMcGoff": "practitioner",
    "Bookfox": "practitioner",
    "BookSummariesEN": "aggregator",
    "BryanJohnson": "practitioner",
    "bigthinkclips": "established_media",
    "B_a_l_t_h_u_s": "practitioner",
}
# Too large relative to the rest of its tier to backfill whole.
SUB_CAPPED = {"bigthink": 300, "asapguide": 200}
# Already covered by an earlier phase — recorded as also_verified_in, not re-added.
SUB_DEDUPE = {"a16z", "NateBJones", "theAIsearch", "ai-foundations", "thekoerneroffice"}


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _load(name: str) -> list[dict[str, Any]]:
    return json.loads((BRONZE / name).read_text())["channels"]


def _norm(handle: str) -> str:
    return handle.lstrip("@").lower()


class SeedBuilder:
    def __init__(self) -> None:
        self.rows: dict[str, dict[str, Any]] = {}

    def add(
        self,
        handle: str,
        name: str,
        videos: int | None,
        domain: str,
        tier: str,
        phase: str,
        note: str,
        subs: int | None = None,
    ) -> None:
        key = _norm(handle)
        if key in self.rows:
            # Already present from an earlier, higher-priority phase. Backfill a
            # video count if this pass has one and the first pass didn't; keep the
            # original classification.
            if videos and not self.rows[key]["videos"]:
                self.rows[key]["videos"] = videos
            self.rows[key]["also_in"].append(phase)
            return
        self.rows[key] = {
            "handle": "@" + handle.lstrip("@"),
            "name": name,
            "videos": videos,
            "domain": domain,
            "authority_tier": tier,
            "phase": phase,
            "note": note,
            "subs": subs,
            "also_in": [],
        }

    def add_research_tier(self) -> None:
        # AWS is deliberately deferred and must be added before the general loop
        # below: it is also present in candidates.json under vendor_primary, and the
        # dedupe-on-first-seen logic in add() would otherwise silently keep whichever
        # classification happened to be seen first rather than the deferred one.
        self.add(
            "amazonwebservices",
            "Amazon Web Services",
            18000,
            "ai_research",
            "vendor_official",
            "research-p3-deferred",
            "18,000 videos, mostly re:Invent breakouts. Ingest by curated playlist, not channel.",
        )
        for r in _load("candidates.json"):
            if not r.get("resolved"):
                continue
            mapped = RESEARCH_TIER_MAP.get(r["category"])
            if mapped is None:
                continue  # hype tier, explicitly excluded
            tier, _default_phase = mapped
            phase = "research-p1" if _norm(r["handle"]) in PHASE1_HANDLES else "research-p2"
            self.add(
                r["handle"],
                r["name"],
                r.get("videos"),
                "ai_research",
                tier,
                phase,
                f"research tier / {r['category']}",
                r.get("subscribers"),
            )

    def add_automation_tier(self) -> None:
        for r in _load("automation_top50.json"):
            if _norm(r["handle"]) in AUTOMATION_EXCLUDE:
                continue
            self.add(
                r["handle"],
                r["name"],
                r.get("videos"),
                "ai_automation",
                "practitioner",
                "automation",
                "automation tier (search-ranked)",
                r.get("subs"),
            )
        self.add(
            "replit",
            "Replit",
            147,
            "ai_automation",
            "vendor_official",
            "automation",
            "platform primary; replaces Zapier",
            126000,
        )
        self.add(
            "marinawyssai",
            "Marina Wyss",
            87,
            "ai_automation",
            "practitioner",
            "automation",
            "ML fundamentals; replaces Julian Goldie",
            151000,
        )

    def add_subscriptions(self) -> None:
        by_handle = {_norm(r["handle"]): r for r in _load("subscriptions_resolved.json")}
        counts_ai = {r["handle"]: r["videos"] for r in _load_raw("subscriptions_counts.json")}
        counts_pd = {r["handle"]: r["videos"] for r in _load_raw("subscriptions_counts_pd.json")}
        all_counts = {**counts_ai, **counts_pd, "bigthink": 9603}

        groups = [
            (SUB_AI_RESEARCH, "ai_research"),
            (SUB_AI_AUTOMATION, "ai_automation"),
            (SUB_ENTREPRENEURSHIP, "entrepreneurship"),
            (SUB_PERSONAL_DEV, "personal_development"),
        ]
        for tiers, domain in groups:
            for handle, tier in tiers.items():
                key = _norm(handle)
                if key in SUB_DEDUPE:
                    continue
                src = by_handle.get(key, {})
                videos = all_counts.get(handle) or all_counts.get(key)
                cap = SUB_CAPPED.get(key)
                note = "subscriptions tier"
                if cap:
                    note = (
                        f"subscriptions tier; CAP at {cap} most-recent, "
                        "archive too large to backfill"
                    )
                self.add(
                    handle,
                    src.get("name", handle),
                    videos,
                    domain,
                    tier,
                    "subscriptions",
                    note,
                    src.get("subs"),
                )

    def emit(self) -> Path:
        out = sorted(
            self.rows.values(), key=lambda r: (r["domain"], r["phase"], -(r["videos"] or 0))
        )
        lines = [HEADER.rstrip("\n"), ""]
        for r in out:
            lines.append(f'- handle: "{r["handle"]}"')
            lines.append(f"  name: {json.dumps(r['name'])}")
            lines.append(f"  domain: {r['domain']}")
            lines.append(f"  authority_tier: {r['authority_tier']}")
            lines.append(f"  phase: {r['phase']}")
            if r["videos"]:
                lines.append(f"  videos_at_survey: {r['videos']}")
            if r["subs"]:
                lines.append(f"  subscribers_at_survey: {r['subs']}")
            lines.append(f"  note: {json.dumps(r['note'])}")
            if r["also_in"]:
                lines.append(f"  also_verified_in: {r['also_in']}")
            lines.append("")

        seed_path = _repo_root() / "seeds" / "youtube_channels.yaml"
        seed_path.write_text("\n".join(lines))

        total_videos = sum(r["videos"] or 0 for r in out)
        print(f"total unique channels: {len(out)}")
        print(f"total long-form videos (uncapped, incl. deferred AWS): {total_videos:,}")
        print("by domain:")
        for domain, count in Counter(r["domain"] for r in out).most_common():
            print(f"  {domain:24} {count}")
        print(f"\nwritten to {seed_path}")
        return seed_path


def _load_raw(name: str) -> list[dict[str, Any]]:
    return json.loads((BRONZE / name).read_text())


def main() -> int:
    builder = SeedBuilder()
    builder.add_research_tier()
    builder.add_automation_tier()
    builder.add_subscriptions()
    builder.emit()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
